var_a <- rep(c("A", "B", "C"),5)
var_b <- rep(c(1,2,3),5)
print (var_a); print (var_b)
matrix1 <- rbind (var_a, var_b)
matrix2 <-cbind (var_a, var_b)
print (matrix1); print (matrix2)
matrix2_new <- as.data.frame(matrix2)
print (matrix2_new)
tapply (var_b, var_a, mean)
tapply (matrix2_new[ ,2], matrix2_new[ ,1], mean)